### ISSUE TITLE
Extra comma after "node-sass-middleware"

### ISSUE THREAD

**Issue by alsoicode** [gautamsi/generator-keystone-ts#1]
When specifying options during the yeoman installation, if you choose sass as your CSS pre-processor, and decline to include an example of emailing with Keystone, there will be an extra comma after the "node-sass-middleware" entry in the resulting package.json.

In turn this causes the npm install to fail.

**Comment by gautamsi** [comment]
should be fixed by aa02f25652281c6f2b3511da10f0775536ae1755 in 0.1.1

**Comment by alsoicode** [comment]
Super! Thanks!
